
@HR.API_HostAddress = http://localhost:5244

@HR.API_HostAddress = http://localhost:5075
@HR.API_HostAddress = http://localhost:7293
GET {{HR.API_HostAddress}}/weatherforecast/
Accept: application/json


